### ISSUE TITLE
NPM RUN DEV  ::SyntaxError: Unexpected token '?'

### ISSUE THREAD

**Issue by royalknight56** [ci010/electron-vue-next#55]
F:\Web\a-electron\vue-ele-next\electron-vue-vite\scripts\rollup.config.js:363
  wait = wait ?? true;
               ^

SyntaxError: Unexpected token '?'
    at Module._compile (internal/modules/cjs/loader.js:895:18)
    at Object.require.extensions.<computed> [as .js] (F:\Web\a-electron\vue-ele-next\electron-vue-vite\node_modules\_rollup@2.45.2@rollup\dist\shared\loadConfigFile.js:540:20)
    at Module.load (internal/modules/cjs/loader.js:815:32)
    at Function.Module._load (internal/modules/cjs/loader.js:727:14)
    at Module.require (internal/modules/cjs/loader.js:852:19)
    at require (internal/modules/cjs/helpers.js:74:18)
    at loadConfigFromBundledFile (F:\Web\a-electron\vue-ele-next\electron-vue-vite\node_modules\_rollup@2.45.2@rollup\dist\shared\loadConfigFile.js:548:42)
    at getDefaultFromTranspiledConfigFile (F:\Web\a-electron\vue-ele-next\electron-vue-vite\node_modules\_rollup@2.45.2@rollup\dist\shared\loadConfigFile.js:532:12)
    at async loadConfigFile (F:\Web\a-electron\vue-ele-next\electron-vue-vite\node_modules\_rollup@2.45.2@rollup\dist\shared\loadConfigFile.js:497:15)
    at async loadAndParseConfigFile (F:\Web\a-electron\vue-ele-next\electron-vue-vite\node_modules\_rollup@2.45.2@rollup\dist\shared\loadConfigFile.js:476:21)

  **wait = wait ?? true; 
fonund on rollup.typescript.plugin.js:108**

**Comment by ci010** [comment]
Ah, it looks like your node does not support `??` operator yet. You can simply replace `??` into `||`, or you can update your node version into 15. 😄
